version: "3"

services:
  sandbox-api:
    container_name: sandbox-api
    build:
      context: .
    ports:
      - '8050:8050'
    environment:
      SERVER_PORT: 8050
      SPRING_DATASOURCE_URL: jdbc:postgresql://employee-postgres:5432/employee
      SPRING_DATASOURCE_USERNAME: employee
      SPRING_DATASOURCE_PASSWORD: employee

  sandbox-front:
    container_name: sandbox-front
    build:
      context: ../sandbox-front
    ports:
      - '4200:4200'

  sandbox-postgres:
    container_name: sandbox-postgres
    image: 'postgres:16.4-alpine'
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: employee
      POSTGRES_PASSWORD: employee
      POSTGRES_DB: employee
