version: "3"

services:
  employee-api:
    container_name: employee-api
    build:
      context: .
    ports:
      - '8050:8050'
    environment:
      SERVER_PORT: 8050
      SPRING_DATASOURCE_URL: jdbc:postgresql://employee-postgres:5432/employee
      SPRING_DATASOURCE_USERNAME: employee
      SPRING_DATASOURCE_PASSWORD: employee

  employee-postgres:
    container_name: employee-postgres
    image: 'postgres:16.4-alpine'
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: employee
      POSTGRES_PASSWORD: employee
      POSTGRES_DB: employee
