server:
  port: 8050

spring:
  threads:
    virtual:
      enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/employee
    username: employee
    password: employee
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      initialization-fail-timeout: 6000

  flyway:
    clean-disabled: false
    clean-on-validation-error: true
    enabled: true
    locations: classpath:/db/migration
